### ISSUE TITLE
Chinese site Ubuntu 16.04 LTS Download is missing

### ISSUE THREAD

**Issue by zprood** [canonical-websites/cn.ubuntu.com#121]
## Summary

[Ubuntu Chinese website has a wrong link for 16.04 LTS (http://cn.ubuntu.com/download/), both 32bit and 64bit link is missing, reported 404.]

## Process

[ I notice that this issue caused by name change of ISO file link, currently old-on website one still is 16.04 LTS, but the latest is 16.04.2 and 16.04 is removed from http://releases.ubuntu.com/16.04/ ]

## Current and expected result

[please fix it with right link to Ubuntu 16.04.2, http://releases.ubuntu.com/16.04/ ]

## Screenshot

[if relevant, include a screenshot]

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue. I will get a fix live shortly.
