### ISSUE TITLE
error

### ISSUE THREAD

**Issue by taikial** [canonical-websites/cn.ubuntu.com#124]
The requested URL /16.04/ubuntu-16.04-desktop-amd64.iso was not found on this server.

Apache/2.4.18 (Ubuntu) Server at releases.ubuntu.com Port 80

**Comment by anthonydillon** [comment]
Thanks for this issue. It has been fixed and will be live shortly.

Duplication of: https://github.com/canonical-websites/cn.ubuntu.com/issues/121

**Comment by deadlight** [comment]
This fix has now been released.
Thanks,
Karl
