### ISSUE TITLE
ubuntu 16.06LTS cannot find the fan

### ISSUE THREAD

**Issue by GoldernRetriever** [canonical-websites/cn.ubuntu.com#127]
## Summary

The fan of my laptop doesn't work even if the cpu is hot. I tried to find the information of the fan by sensors but there's no massage about the fan. 

my laptop is dell xps-13 and the system is ubuntu 16.04LTS

**Comment by pmahnke** [comment]
@GoldernRetriever 

You mistakenly filed this against the chinese website repo... we can't answer support questions.

We suggest you try http://askubuntu.com/ or dell itself to get some help.

I hope that helps.

Peter
