### ISSUE TITLE
importerror: no module named packaging.version

### ISSUE THREAD

**Issue by xubo0321** [canonical-websites/cn.ubuntu.com#134]
when i insert : sudo make pycaffe or catkin_make  this error is always appearing

**Comment by deadlight** [comment]
@xubo0321 can you please clarify what you are attempting to do, the steps required to replicate the issue you are seeing and what your desired result would be. 

Thanks,
Karl

**Comment by deadlight** [comment]
I don't think that this issue is anything to do with the cn.ubuntu.com website. If it is then feel free to reopen it and add more information about the bug.
Karl
