### ISSUE TITLE
The "Ubuntu Core" link on the IoT page is returning a 404

### ISSUE THREAD

**Issue by caldav** [canonical-websites/cn.ubuntu.com#140]
On http://cn.ubuntu.com/internet-of-things/, the link for developers at the bottom of the page is returning a 404. It should be changed to https://developer.ubuntu.com/core

![screenshot from 2017-05-30 12-34-43](https://cloud.githubusercontent.com/assets/18480003/26579528/86d49520-4534-11e7-8cf5-d567fbc37df3.png)

**Comment by deadlight** [comment]
Thanks for the report. I've updated the link in the CMS.
