### ISSUE TITLE
New takeover

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/cn.ubuntu.com#145]

**Comment by yaili** [comment]
Takeover layout, based on previous banners by Tom **(I couldn't get Illustrator to accept the text for the button that is in the brief, so please replace the word "Button")**

![ubuntu-china-hackaton](https://user-images.githubusercontent.com/223966/29320655-d1c82c5e-81cf-11e7-9d84-cef6282bb359.png)

- Background image: https://assets.ubuntu.com/v1/e8e347fa-ubuntu-hackaton-takeover-bkg.png
- Logo: https://assets.ubuntu.com/v1/6b186d2d-ubuntu-jam.svg
- Title in heading-1
- Text below in heading-5
- Brief: https://docs.google.com/document/d/1f-RMDSjHNC0cDGZclWcVWsSlB7O-WIGIGuK6aJE1Fm4/edit?ts=5992b31e#

**Comment by yaili** [comment]
Another note: I've copied the text from the Photoshop file I received, but I don't see it in the brief or in the links inside the brief. Maybe I missed it.

**Comment by deadlight** [comment]
@yaili I think that the original plan was for us to use the image without actually having the copy in the HTML. I've asked them to provide us with the full text. Thanks for the spot.
