### ISSUE TITLE
Visual review - cn.ubuntu.com / cloud

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/cn.ubuntu.com#170]
### Public cloud 
- [x] update to @anthonydillon new inline image component so that all logos fit on one line

### Cloud tools
- [x] add external link icon to headings

### Services or support
- [ ] update image position to: bottom-right; as seen [here](https://raw.githubusercontent.com/ubuntudesign/vanilla-design/master/Image%20positioning/image-positioning.png)

**Comment by barrymcgee** [comment]
Not actioning the final point here as @kwm14 and I agreed in Slack chat it wasn't suitable.
