### ISSUE TITLE
触摸板的轻触变成了次键的点击；

### ISSUE THREAD

**Issue by wangmeng2017** [canonical-websites/cn.ubuntu.com#181]
## 触摸板的轻触变成了次键的点击
Ubuntu17.04  64位，dell-Inspiron-3568，sogoupinyin2.1.0.0068_amd64.deb
安装搜狗输入法之前没有这个问题，设置鼠标主键为右键后，触摸板的轻触还是主键的点击；
用dpkg -i sogoupinyin安装搜狗输入法时，先是3、4行提示安装了什么什么，然后提示“有错误发生”（没有更多的信息），就退出命令了。
然后我重启了系统。
重启之后，搜狗拼音可以用，但是触摸板的轻触就变成了次键的点击；不管鼠标的主键设置成左键还是右键，都没有用。

## Current and expected result

希望能让触摸板回复正常。

**Comment by anthonydillon** [comment]
对不起，听到您的触摸板有问题。不幸的是，由于我是网络团队的成员，我无法通过此渠道提供支持。

如果您可以在https://bugs.launchpad.net/ubuntu上报告Ubuntu上的错误，或者在askubuntu.com上询问您的问题，您应该会收到一个快速回复。

**Comment by wangmeng2017** [comment]
谢谢！
