### ISSUE TITLE
ubuntu-17.10.1-desktop-amd64    dock设置为底部后，新开启程序窗口无法显示

### ISSUE THREAD

**Issue by A-Little-Ant** [canonical-websites/cn.ubuntu.com#185]
## Summary
新安装乌班图17.10.1，设置dock位置为底部，“设置”窗口消失，“设置”的图标还是dock上显示。打开其他应用，比如“茄子”，一样只显示图标不显示窗口。“终端”命令行窗口显示正常。这样子造成很多应用没办法使用（不显示窗口界面）
## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]
![2018-02-10 23-39-52](https://user-images.githubusercontent.com/15061102/36063757-10d81a66-0ebc-11e8-88f9-0de0c7922823.png)

**Comment by anthonydillon** [comment]
This repository is for issues with the website. For issues with the operating system please file them on here: http://launchpad.net/Ubuntu.
