### ISSUE TITLE
16.04 LTS Download link is out of date

### ISSUE THREAD

**Issue by zprood** [canonical-websites/cn.ubuntu.com#187]
## Summary
Currently, the new version of 16.04 LTS is updated to 16.04.4, but the link is for 16.04.3. Like this
_http://releases.ubuntu.com/16.04/ubuntu-16.04.3-desktop-amd64.iso_

## Effect Download Links: 

Ubuntu 16.04 LTS(长期支持)版本: 32\64 bit.
64bit: http://releases.ubuntu.com/16.04/ubuntu-16.04.3-desktop-amd64.iso
32bit: http://releases.ubuntu.com/16.04/ubuntu-16.04.3-desktop-i386.iso

## Fix
Please replace these two links with:
64bit: http://releases.ubuntu.com/16.04.4/ubuntu-16.04.4-desktop-amd64.iso
32bit: http://releases.ubuntu.com/16.04.4/ubuntu-16.04.4-desktop-i386.iso

**Comment by anthonydillon** [comment]
Thank you very much for this issue. We will get this updated as soon as possible.
