### ISSUE TITLE
ubuntu kylin

### ISSUE THREAD

**Issue by yanghuancheng** [canonical-websites/cn.ubuntu.com#188]
## Summary

Ubuntu kylin 17.04 LTS (32bit & 64bit) can not be downloaded form cn.ubuntyu.com/download

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/26289842/37322659-e679f1c0-26b9-11e8-9609-539920f4d7a2.png)

**Comment by anthonydillon** [comment]
Thank you very much for reporting this issue. We need to remove the Kylin download links.
