### ISSUE TITLE
China website banner - takeover banner

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/cn.ubuntu.com#200]
## Summary

[please describe the issue]

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by anasereijo** [comment]
@steverydz 

**logo sizes:**
- Ubuntu logo: 168x38
- Orange pi: 131x46px

**illustration size:**
250x207px

**assets:**
https://assets.ubuntu.com/v1/c4e47210-logo-ubuntu-orange.svg
https://assets.ubuntu.com/v1/02251698-orange-pi-logo.png
https://assets.ubuntu.com/v1/f5b47308-china-banner-takeover-background.jpg
https://assets.ubuntu.com/v1/070a8839-china-takeover-illustration.svg

**final design:**
![china-banner-takeover](https://user-images.githubusercontent.com/36884067/37837487-3d41fbce-2ead-11e8-8bf2-c59b111b47dd.jpg)

**Comment by steverydz** [comment]
@anasereijo Could you please paste the text into this issue too?

**Comment by anasereijo** [comment]
@steverydz you can find the text here:
https://docs.google.com/document/d/1pCnGI3p4m53saxqqvdJAhV25XpFUMTmDs_7HDvF9XLI/edit

**Comment by steverydz** [comment]
@anasereijo Thanks. The orange logo has black text? https://assets.ubuntu.com/v1/02251698-orange-pi-logo.png

**Comment by anasereijo** [comment]
@steverydz thanks for checking that. That was the logo saved on assets. I saved a new one: https://assets.ubuntu.com/v1/592495ad-orangepi-whitetext.svg
