### ISSUE TITLE
Chinese words error on the CN desktop home page.

### ISSUE THREAD

**Issue by feitill** [canonical-websites/cn.ubuntu.com#210]
## Summary

There is a Chinese word error on the CN desktop home page.,https://cn.ubuntu.com/desktop/.
"**Snapcraft**
snap是全新的Linux应用格式包，拥有更安全、稳定、易维护更新等特点。snap又snapcraft打包而来，现在就开始制作自己的snap吧！" The word "又" is wrong at here.
## Process

Modify the word "又" to the right one,"由".

## Current and expected result

Modification of the wrong.

## Screenshot

[if relevant, include a screenshot]
![default](https://user-images.githubusercontent.com/30235792/39351307-ad72754e-4a33-11e8-9255-487bf88a36c1.png)

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue. We will triage and have this issue resolved shortly.

**Comment by anthonydillon** [comment]
@zprood could you please confirm this issue.

**Comment by zprood** [comment]
Sure, will solve this in next PR.

**Comment by zprood** [comment]
Fixed.
