### ISSUE TITLE
Update the IoT store image with snapcraft.io

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/cn.ubuntu.com#211]
Update the image on the iot page with a new one from snapcraft.io.

https://cn.ubuntu.com/internet-of-things/

**Comment by lyubomir-popov** [comment]
Would this do? 
https://assets.ubuntu.com/v1/313be7a3-snapcraft.io_store.png

**Comment by zprood** [comment]
This image is for snapcraft and snap on desktop and server but not for
Ubuntu Core, we'd like to keep the current image for IoT. Also if there is
new update on English site, I will update this.

**Comment by anthonydillon** [comment]
Snapcraft is replacing the current store. How do you even get to that store?

**Comment by zprood** [comment]
Hmm, yes please update the image, my information is out of date for the
store. :D

**Comment by frankiegranato** [comment]
Looks like this is done. I'm closing the ticket :-)

**Comment by anthonydillon** [comment]
Sorry this issue was still in review.

**Comment by zprood** [comment]
I notice that EN site has replaced the store screenshot, so maybe we can do that same thing for China site.  https://www.ubuntu.com/internet-of-things

**Comment by anthonydillon** [comment]
Done
