### ISSUE TITLE
Ubuntu 18.04 has been released, but the Chinese website says "3 months before the official release."

### ISSUE THREAD

**Issue by njlyf2011** [canonical-websites/cn.ubuntu.com#213]
Ubuntu 18.04 has been released, but the Chinese website says "3 months before the official release."

**Comment by njlyf2011** [comment]
![default](https://user-images.githubusercontent.com/18372244/39402383-671b83f2-4b90-11e8-84a5-3c5f329f2829.png)

**Comment by zprood** [comment]
Thanks for the feedback, will update soon.

**Comment by njlyf2011** [comment]
Thanks...

**Comment by zprood** [comment]
Fixed.
