### ISSUE TITLE
使用Ubuntu18.04制作的U盘安装，进入安装界面界面卡住，按钮不能点击，只能强制关机。每次都会卡住，电脑风扇也会转起来

### ISSUE THREAD

**Issue by starnic** [canonical-websites/cn.ubuntu.com#215]
## Summary

[please describe the issue]

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by zprood** [comment]
你好，系统安装问题非网站bug，麻烦到社区或者搜索引擎寻找答案。谢谢！
