### ISSUE TITLE
关于ubuntu18.04中，如何设置全局代理

### ISSUE THREAD

**Issue by Lxmic** [canonical-websites/cn.ubuntu.com#217]
## Summary

chrome中可是通过插件使用vpn，但是我在安装dropbox的时候，没法连接外网，无法进行全局代理。16.04的时候可以很容易的安装。

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by zprood** [comment]
该问题与Ubuntu中文站网站无关，故关闭。
