### ISSUE TITLE
Ubuntu16.04  when use preseed install ,When multi NIC, it will stop installation and manual operation.

### ISSUE THREAD

**Issue by zhangningmeng** [canonical-websites/cn.ubuntu.com#223]
When multi network card is installed ubuntu16.04, it will stop installation and manual operation., and choose the network card to use during the installation process.

**Comment by steverydz** [comment]
Hi @zhangningmeng, this looks like you are trying to file a bug against Ubuntu itself, rather than the website. To do that please [use this link](https://help.ubuntu.com/community/ReportingBugs). Thanks.
