### ISSUE TITLE
The manual Network Proxy is not work in Ubuntu 18.04.

### ISSUE THREAD

**Issue by lizhe2018** [canonical-websites/cn.ubuntu.com#227]
## Summary

I need use Ubuntu-18.04 with setting Network Proxy manually. I did it, but it didn't work.

## Process

I don't know what I should do now.

## Current and expected result

It can work that setting Network Proxy manually.

## Screenshot

![capture](https://user-images.githubusercontent.com/36813974/44076959-a814bc5a-9fd4-11e8-9d2b-b0e37b562716.PNG)

**Comment by zprood** [comment]
This isn't the website issue, you can try search engine. 
Close it.
