### ISSUE TITLE
webkit2gtk-4.0-dev 依赖关系不完整

### ISSUE THREAD

**Issue by rocket049** [canonical-websites/cn.ubuntu.com#239]
## Summary

webkit2gtk-4.0-dev中的WebKitFrame.h、WebKitJavascriptResult.h 都有 #include <jsc/jsc.h>，
但是“jsc/jsc.h”文件不存在。

## Process

apt install libwebkit2gtk-4.0-dev golang-go

go get -v github.com/sourcegraph/go-webkit2/webkit2

## Current and expected result

report error:

```
# github.com/sourcegraph/go-webkit2/webkit2
In file included from /usr/include/webkitgtk-4.0/webkit2/webkit2.h:54:0,
                 from ../../github.com/sourcegraph/go-webkit2/webkit2/settings.go:3:
/usr/include/webkitgtk-4.0/webkit2/WebKitJavascriptResult.h:28:10: fatal error: jsc/jsc.h: No such file or directory
 #include <jsc/jsc.h>
          ^~~~~~~~~~~
compilation terminated.
```

it should run correct.

## Screenshot

![2018-10-04 22-12-54](https://user-images.githubusercontent.com/40598197/46479932-be2f1500-c822-11e8-8406-551fe25fe4df.png)

**Comment by zprood** [comment]
Please report the bug on https://launchpad.net, the issue is just for content of website.
