### ISSUE TITLE
CMS - Fix version comparison

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/cn.ubuntu.com#47]
Go into a page in the CMS admin, click "history", try comparing two revisions. You should get an error.

Now fix it.

**Comment by anthonydillon** [comment]
@nottrobin Do we need a CMS?

**Comment by pmahnke** [comment]
@nottrobin and @anthonydillon no we do not... we are going to make this a 1 or 2 page site... likely static

**Comment by anthonydillon** [comment]
Good to know, these issues are due to die shortly then.

**Comment by nottrobin** [comment]
Yep. Not worth fixing.
