### ISSUE TITLE
[iPhone 6 - iOS] download page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/cn.ubuntu.com#60]
No padding below the box. Touching the border of the next row.
![bs_realios_mobile_iphone 6-8 0 2](https://cloud.githubusercontent.com/assets/1413534/11878331/0ffe7d0a-a4ed-11e5-9430-4a2a86cb4dfb.jpg)

**Comment by deadlight** [comment]
Just verified on an iPhone. It's better now but still not right.
