### ISSUE TITLE
[iPad 4] Image not touching the border

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/cn.ubuntu.com#61]
![bs_realios_tablet_ipad 4-7 0](https://cloud.githubusercontent.com/assets/1413534/11878437/be9bf4d2-a4ed-11e5-9ac3-e8b556693a70.jpg)

**Comment by deadlight** [comment]
Implementing more of vanilla's features should get this in line with Ubuntu.com

**Comment by anthonydillon** [comment]
Looks like this page has changed now and removed the issues.
