### ISSUE TITLE
[IE8] Logo and global nav do not display correctly

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/cn.ubuntu.com#63]
Can we fix the logo as its an important navigation item. Can you look into the global nav style for IE8 please.

![bs_win7_ie_8 0](https://cloud.githubusercontent.com/assets/1413534/11878799/abd175be-a4ef-11e5-9379-1ece26e2f0d1.jpg)

**Comment by deadlight** [comment]
Updating Vanilla and implementing more Vanilla features could help here.
